import Foundation

enum ExportFormatter {

    // MARK: - Plain Text

    static func plainText(for report: AudioFileReport) -> String {
        var lines: [String] = []
        lines.append("LUnette — Loudness Analysis Report")
        lines.append(String(repeating: "─", count: 44))
        lines.append("File:              \(report.filename)")
        lines.append("Codec:             \(report.codec)")
        lines.append("Sample Rate:       \(Int(report.sampleRate)) Hz")
        lines.append("Bit Depth:         \(report.bitDepthLabel)")
        lines.append("Channels:          \(report.channels)")
        lines.append("Duration:          \(durationString(report.duration))")
        lines.append(String(repeating: "─", count: 44))
        lines.append("Integrated:        \(lufsStr(report.integratedLUFS))")
        lines.append("LRA:               \(String(format: "%.1f", report.lra)) LU")
        lines.append("LRA Low:           \(lufsStr(report.lraLow))")
        lines.append("LRA High:          \(lufsStr(report.lraHigh))")
        lines.append("LRA Threshold:     \(lufsStr(report.lraThreshold))")
        lines.append("Int. Threshold:    \(lufsStr(report.integratedThreshold))")
        lines.append(String(repeating: "─", count: 44))
        lines.append("True Peak L:       \(dbTPStr(report.truePeakL))")
        lines.append("True Peak R:       \(dbTPStr(report.truePeakR))")
        lines.append("True Peak Max:     \(dbTPStr(report.truePeakMax))")
        lines.append("PLR:               \(String(format: "%+.1f", report.plr)) dB")
        lines.append("Momentary Max:     \(lufsStr(report.momentaryMax))")
        lines.append("Short-term Max:    \(lufsStr(report.shortTermMax))")
        if report.clipFlag != .none {
            lines.append("Clip Warning:      \(report.clipFlag == .error ? "CLIP" : "NEAR CLIP")")
        }
        lines.append(String(repeating: "─", count: 44))
        lines.append("Platform Compliance:")
        for std in LoudnessStandard.all {
            let badge    = std.badge(for: report)
            let delta    = std.gainDelta(for: report)
            let deltaStr = String(format: delta >= 0.0 ? "+%.1f" : "%.1f", delta)
            let name     = std.name.padding(
                toLength: 14,
                withPad: " ",
                startingAt: 0
            )
            let target = String(format: "%5d", Int(std.targetLUFS))
            lines.append("  \(name) \(target) LUFS  \(deltaStr) LU  \(badge.label)")
        }
        lines.append(String(repeating: "─", count: 44))
        lines.append("Generated by LUnette · \(isoDate())")
        return lines.joined(separator: "\n")
    }

    // MARK: - CSV

    static func csv(for reports: [AudioFileReport]) -> String {
        var rows: [String] = []
        let header = [
            "Filename", "Codec", "SampleRate", "BitDepth", "Channels", "Duration",
            "Integrated_LUFS", "LRA_LU", "LRA_Low", "LRA_High", "LRA_Threshold", "Int_Threshold",
            "TruePeak_L_dBTP", "TruePeak_R_dBTP", "TruePeak_Max_dBTP",
            "PLR_dB", "Momentary_Max_LUFS", "ShortTerm_Max_LUFS", "Clip_Flag"
        ].joined(separator: ",")
        rows.append(header)

        for r in reports {
            let row: [String] = [
                csvEscape(r.filename),
                csvEscape(r.codec),
                String(Int(r.sampleRate)),
                String(r.bitDepth),
                String(r.channels),
                String(format: "%.2f", r.duration),
                format(r.integratedLUFS),
                format(r.lra),
                format(r.lraLow),
                format(r.lraHigh),
                format(r.lraThreshold),
                format(r.integratedThreshold),
                format(r.truePeakL),
                format(r.truePeakR),
                format(r.truePeakMax),
                String(format: "%.2f", r.plr),
                format(r.momentaryMax),
                format(r.shortTermMax),
                clipLabel(r.clipFlag)
            ]
            rows.append(row.joined(separator: ","))
        }
        return rows.joined(separator: "\n")
    }

    // MARK: - Helpers

    private static func lufsStr(_ v: Double) -> String {
        v.isFinite ? String(format: "%.1f LUFS", v) : "—"
    }

    private static func dbTPStr(_ v: Double) -> String {
        v.isFinite ? String(format: "%.2f dBTP", v) : "—"
    }

    private static func format(_ v: Double) -> String {
        v.isFinite ? String(format: "%.2f", v) : ""
    }

    private static func clipLabel(_ f: ClipFlag) -> String {
        switch f {
        case .none:    return ""
        case .warning: return "WARN"
        case .error:   return "CLIP"
        }
    }

    private static func durationString(_ t: TimeInterval) -> String {
        let h = Int(t) / 3600
        let m = (Int(t) % 3600) / 60
        let s = Int(t) % 60
        if h > 0 { return String(format: "%d:%02d:%02d", h, m, s) }
        return String(format: "%d:%02d", m, s)
    }

    /// Escapes a CSV field, also prefixing `=`, `+`, `-`, `@` with a single quote so
    /// spreadsheet apps treat the cell as text rather than a formula (CSV injection).
    private static func csvEscape(_ s: String) -> String {
        var safe = s
        if let first = safe.first, "=+-@".contains(first) {
            safe = "'" + safe
        }
        if safe.contains(",") || safe.contains("\"") || safe.contains("\n") {
            let escaped = safe.replacingOccurrences(of: "\"", with: "\"\"")
            return "\"" + escaped + "\""
        }
        return safe
    }

    private static func isoDate() -> String {
        let f = ISO8601DateFormatter()
        f.formatOptions = [.withFullDate, .withTime, .withColonSeparatorInTime]
        return f.string(from: Date())
    }
}
